// <auto-generated />
using System;
using FIAP.CP2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FIAP.CP2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251021210136_AdicionarMetodosPagamento")]
    partial class AdicionarMetodosPagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIAP.CP2.Model.ContaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Ativa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Saldo")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("FIAP.CP2.Model.MetodoPagamentoModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ContaId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoMetodo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("MetodosPagamento");
                });

            modelBuilder.Entity("FIAP.CP2.Model.TransacaoModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ContaDestinoId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ContaId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("SaldoAnterior")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("SaldoPosterior")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Valor")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
